---
abstract: 'Minimal PlugAuth client'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PlugAuth-Client-Tiny
requires:
  HTTP::Tiny: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/plicease/plugauth-client-tiny/issues
  homepage: http://perl.wdlabs.com/PlugAuth-Client-Tiny/
  repository: git://github.com/plicease/plugauth-client-tiny.git
version: 0.01
